"""Newsletter now works with ids

Revision ID: 5ac0599c63fe
Revises: 
Create Date: 2024-02-14 14:16:46.364611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac0599c63fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cronicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cronicas', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
